name: Build and Test App
on:
  push:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: List files in the repository
      run: |
        tree -L 2 ./
    - name: Install npm dependencies
      run: npm install --prefix client
    - name: Build with npm
      env:
         CI: "" # ignores warnings
      run: npm run build --prefix client
    - name: Run with npm
      run: npm run start --prefix client &
    - name: Run Selenium tests
      run: python tests/selenium/test01.py